#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLSV")]
	public partial class QLSVDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_LopHoc(tbl_LopHoc instance);
    partial void Updatetbl_LopHoc(tbl_LopHoc instance);
    partial void Deletetbl_LopHoc(tbl_LopHoc instance);
    partial void Inserttbl_SinhVien(tbl_SinhVien instance);
    partial void Updatetbl_SinhVien(tbl_SinhVien instance);
    partial void Deletetbl_SinhVien(tbl_SinhVien instance);
    #endregion
		
		public QLSVDataContext() : 
				base(global::QLSV.Properties.Settings.Default.QLSVConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLSVDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLSVDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLSVDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLSVDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_LopHoc> tbl_LopHocs
		{
			get
			{
				return this.GetTable<tbl_LopHoc>();
			}
		}
		
		public System.Data.Linq.Table<tbl_SinhVien> tbl_SinhViens
		{
			get
			{
				return this.GetTable<tbl_SinhVien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_LopHoc")]
	public partial class tbl_LopHoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _malop;
		
		private string _tenlop;
		
		private string _khoa;
		
		private string _nienkhoa;
		
		private System.Nullable<short> _siso;
		
		private EntitySet<tbl_SinhVien> _tbl_SinhViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmalopChanging(string value);
    partial void OnmalopChanged();
    partial void OntenlopChanging(string value);
    partial void OntenlopChanged();
    partial void OnkhoaChanging(string value);
    partial void OnkhoaChanged();
    partial void OnnienkhoaChanging(string value);
    partial void OnnienkhoaChanged();
    partial void OnsisoChanging(System.Nullable<short> value);
    partial void OnsisoChanged();
    #endregion
		
		public tbl_LopHoc()
		{
			this._tbl_SinhViens = new EntitySet<tbl_SinhVien>(new Action<tbl_SinhVien>(this.attach_tbl_SinhViens), new Action<tbl_SinhVien>(this.detach_tbl_SinhViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_malop", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string malop
		{
			get
			{
				return this._malop;
			}
			set
			{
				if ((this._malop != value))
				{
					this.OnmalopChanging(value);
					this.SendPropertyChanging();
					this._malop = value;
					this.SendPropertyChanged("malop");
					this.OnmalopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenlop", DbType="NVarChar(50)")]
		public string tenlop
		{
			get
			{
				return this._tenlop;
			}
			set
			{
				if ((this._tenlop != value))
				{
					this.OntenlopChanging(value);
					this.SendPropertyChanging();
					this._tenlop = value;
					this.SendPropertyChanged("tenlop");
					this.OntenlopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khoa", DbType="NVarChar(50)")]
		public string khoa
		{
			get
			{
				return this._khoa;
			}
			set
			{
				if ((this._khoa != value))
				{
					this.OnkhoaChanging(value);
					this.SendPropertyChanging();
					this._khoa = value;
					this.SendPropertyChanged("khoa");
					this.OnkhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nienkhoa", DbType="NVarChar(50)")]
		public string nienkhoa
		{
			get
			{
				return this._nienkhoa;
			}
			set
			{
				if ((this._nienkhoa != value))
				{
					this.OnnienkhoaChanging(value);
					this.SendPropertyChanging();
					this._nienkhoa = value;
					this.SendPropertyChanged("nienkhoa");
					this.OnnienkhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siso", DbType="SmallInt")]
		public System.Nullable<short> siso
		{
			get
			{
				return this._siso;
			}
			set
			{
				if ((this._siso != value))
				{
					this.OnsisoChanging(value);
					this.SendPropertyChanging();
					this._siso = value;
					this.SendPropertyChanged("siso");
					this.OnsisoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_LopHoc_tbl_SinhVien", Storage="_tbl_SinhViens", ThisKey="malop", OtherKey="malop")]
		public EntitySet<tbl_SinhVien> tbl_SinhViens
		{
			get
			{
				return this._tbl_SinhViens;
			}
			set
			{
				this._tbl_SinhViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_SinhViens(tbl_SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.tbl_LopHoc = this;
		}
		
		private void detach_tbl_SinhViens(tbl_SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.tbl_LopHoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_SinhVien")]
	public partial class tbl_SinhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _mssv;
		
		private string _hoten;
		
		private string _gioitinh;
		
		private System.Nullable<System.DateTime> _ngaysinh;
		
		private string _malop;
		
		private EntityRef<tbl_LopHoc> _tbl_LopHoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmssvChanging(string value);
    partial void OnmssvChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    partial void OnngaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaysinhChanged();
    partial void OnmalopChanging(string value);
    partial void OnmalopChanged();
    #endregion
		
		public tbl_SinhVien()
		{
			this._tbl_LopHoc = default(EntityRef<tbl_LopHoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mssv", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mssv
		{
			get
			{
				return this._mssv;
			}
			set
			{
				if ((this._mssv != value))
				{
					this.OnmssvChanging(value);
					this.SendPropertyChanging();
					this._mssv = value;
					this.SendPropertyChanged("mssv");
					this.OnmssvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(50)")]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NVarChar(50)")]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_malop", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string malop
		{
			get
			{
				return this._malop;
			}
			set
			{
				if ((this._malop != value))
				{
					if (this._tbl_LopHoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmalopChanging(value);
					this.SendPropertyChanging();
					this._malop = value;
					this.SendPropertyChanged("malop");
					this.OnmalopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_LopHoc_tbl_SinhVien", Storage="_tbl_LopHoc", ThisKey="malop", OtherKey="malop", IsForeignKey=true)]
		public tbl_LopHoc tbl_LopHoc
		{
			get
			{
				return this._tbl_LopHoc.Entity;
			}
			set
			{
				tbl_LopHoc previousValue = this._tbl_LopHoc.Entity;
				if (((previousValue != value) 
							|| (this._tbl_LopHoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_LopHoc.Entity = null;
						previousValue.tbl_SinhViens.Remove(this);
					}
					this._tbl_LopHoc.Entity = value;
					if ((value != null))
					{
						value.tbl_SinhViens.Add(this);
						this._malop = value.malop;
					}
					else
					{
						this._malop = default(string);
					}
					this.SendPropertyChanged("tbl_LopHoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
