<?xml version="1.0" encoding="utf-8"?><Database Name="QLSV" Class="QLSVDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ADMIN-PC\SQLEXPRESS;Initial Catalog=QLSV;Persist Security Info=True;User ID=sa;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="QLSV.Properties.Settings" SettingsPropertyName="QLSVConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_LopHoc" Member="tbl_LopHocs">
    <Type Name="tbl_LopHoc">
      <Column Name="malop" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenlop" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="khoa" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="nienkhoa" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="siso" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="tbl_LopHoc_tbl_SinhVien" Member="tbl_SinhViens" ThisKey="malop" OtherKey="malop" Type="tbl_SinhVien" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_SinhVien" Member="tbl_SinhViens">
    <Type Name="tbl_SinhVien">
      <Column Name="mssv" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="hoten" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="gioitinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ngaysinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="malop" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="tbl_LopHoc_tbl_SinhVien" Member="tbl_LopHoc" ThisKey="malop" OtherKey="malop" Type="tbl_LopHoc" IsForeignKey="true" />
    </Type>
  </Table>
</Database>